### ISSUE TITLE
ghcjs support

### ISSUE THREAD

**Issue by SamuraiJack** [rikvdkleij/intellij-haskell#191]
Great Haskell IDE, thanks for your work!

ghcjs support would make it even better :)

I'm ready to help with that.

**Comment by rikvdkleij** [comment]
Thanks!

What do you expect from GHCJS support?

Btw, I'm currently busy with rewrite to support multipackage projects and to make plugin more solid. Also still a lot of other issues to solve which have more prio. So maybe in the future.

**Comment by SamuraiJack** [comment]
ghcjs support will give you the souls of all the web-dev haskellers (at glance on irc: #ghcjs - 71 user, #reflex-frp - 63 users). Normal basic functionality, like jump to definition and rename identifier will make the quality of our dev live better :) 

The primary workflow with ghcjs is the same as with ghc, using stack. The main difference is that in stack.yaml there's a different compiler:

```
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
```
So everything is compiled with ghcjs and executables should be launched with nodejs. Right now it seems to compile/install all the libs as in normal ghc case, but ctrl+click does not work. Do you have an idea why? Some module can't be compiled with ghcjs (expect to produce native binary)?
