### ISSUE TITLE
Remote stack.yaml package with subdirectories causes problems

### ISSUE THREAD

**Issue by iand675** [rikvdkleij/intellij-haskell#209]
I have the following package configuration in the `packages:` list in my stack.yaml, and when I try to import from existing sources I get the error in the attached screenshot:

```yaml

- location:
    git: https://github.com/iand675/dd-middleware.git
    commit: ffdfae6268c36329d0c02776d0800199615bc9f8
  subdirs:
  - dd-wai-middleware
  - dd-yesod-middleware
  extra-dep: true

```

<img width="410" alt="this_should_not_be_shown_and_welcome_to_intellij_idea" src="https://user-images.githubusercontent.com/69209/29645193-d7120e6c-88b6-11e7-8baa-f6ca2830ae83.png">
