### ISSUE TITLE
Multiple internall librearies not marked  correctly

### ISSUE THREAD

**Issue by majkrzak** [rikvdkleij/intellij-haskell#577]
When dealing with following `package.yaml`

```yaml
internal-libraries:
  foo-core:
    source-dirs: src/core
  foo-application:
    source-dirs: src/application
    dependencies:
    - foo-core

executable:
  main:                Main.hs
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - foo-core
  - foo-application:
```

1. `src/core` is not marked as source directory
2. Restarting repl fails with: `Error parsing targets: Component CLib does not exist in package foo`
   Can be solved by adding dummy `library:`
